CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$ BEGIN
    CREATE TYPE email_provider_type AS ENUM ('smtp', 'sendgrid', 'mailgun', 'aws_ses', 'resend', 'postmark');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE storage_provider_type AS ENUM ('local', 'aws_s3', 'azure_blob', 'gcp_storage', 'digitalocean_spaces');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE log_level_type AS ENUM ('debug', 'info', 'warn', 'error', 'fatal');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE twitter_card_type AS ENUM ('summary', 'summary_large_image', 'app', 'player');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS public.system_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    system_name TEXT NOT NULL DEFAULT 'BuildFlow ERP',
    system_tagline TEXT,
    system_description TEXT,
    logo_url TEXT,
    logo_light_url TEXT,
    logo_dark_url TEXT,
    favicon_url TEXT,
    login_logo_url TEXT,
    email_logo_url TEXT,
    meta_title TEXT,
    meta_description TEXT,
    meta_keywords TEXT[],
    og_image_url TEXT,
    og_title TEXT,
    og_description TEXT,
    twitter_card_type twitter_card_type DEFAULT 'summary_large_image',
    twitter_site TEXT,
    twitter_creator TEXT,
    google_analytics_id TEXT,
    google_tag_manager_id TEXT,
    facebook_pixel_id TEXT,
    custom_tracking_code TEXT,
    custom_head_scripts TEXT,
    custom_body_scripts TEXT,
    ad_network_enabled BOOLEAN NOT NULL DEFAULT false,
    ad_network_code TEXT,
    ad_placement_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    support_email TEXT,
    support_phone TEXT,
    support_address JSONB,
    social_links JSONB NOT NULL DEFAULT '{}'::jsonb,
    legal_links JSONB NOT NULL DEFAULT '{}'::jsonb,
    email_provider email_provider_type DEFAULT 'smtp',
    smtp_host TEXT,
    smtp_port INTEGER DEFAULT 587,
    smtp_user TEXT,
    smtp_password_encrypted TEXT,
    smtp_from_email TEXT,
    smtp_from_name TEXT,
    smtp_use_tls BOOLEAN NOT NULL DEFAULT true,
    smtp_use_ssl BOOLEAN NOT NULL DEFAULT false,
    sendgrid_api_key_encrypted TEXT,
    sendgrid_from_email TEXT,
    sendgrid_from_name TEXT,
    mailgun_api_key_encrypted TEXT,
    mailgun_domain TEXT,
    mailgun_region TEXT DEFAULT 'us',
    aws_ses_region TEXT,
    aws_ses_access_key_encrypted TEXT,
    aws_ses_secret_key_encrypted TEXT,
    aws_ses_from_email TEXT,
    aws_ses_from_name TEXT,
    resend_api_key_encrypted TEXT,
    resend_from_email TEXT,
    resend_from_name TEXT,
    postmark_api_key_encrypted TEXT,
    postmark_from_email TEXT,
    postmark_from_name TEXT,
    email_test_mode BOOLEAN NOT NULL DEFAULT false,
    email_test_recipient TEXT,
    password_min_length INTEGER NOT NULL DEFAULT 8,
    password_max_length INTEGER NOT NULL DEFAULT 128,
    password_require_uppercase BOOLEAN NOT NULL DEFAULT true,
    password_require_lowercase BOOLEAN NOT NULL DEFAULT true,
    password_require_numbers BOOLEAN NOT NULL DEFAULT true,
    password_require_symbols BOOLEAN NOT NULL DEFAULT false,
    password_expiry_days INTEGER,
    password_history_count INTEGER DEFAULT 5,
    session_timeout_minutes INTEGER NOT NULL DEFAULT 60,
    session_absolute_timeout_hours INTEGER DEFAULT 24,
    max_concurrent_sessions INTEGER DEFAULT 5,
    max_login_attempts INTEGER NOT NULL DEFAULT 5,
    lockout_duration_minutes INTEGER NOT NULL DEFAULT 30,
    progressive_lockout BOOLEAN NOT NULL DEFAULT true,
    require_email_verification BOOLEAN NOT NULL DEFAULT true,
    email_verification_expires_hours INTEGER NOT NULL DEFAULT 24,
    enable_two_factor BOOLEAN NOT NULL DEFAULT false,
    force_two_factor_for_roles TEXT[] DEFAULT '{}',
    enable_captcha BOOLEAN NOT NULL DEFAULT false,
    captcha_provider TEXT DEFAULT 'recaptcha_v3',
    captcha_site_key TEXT,
    captcha_secret_key_encrypted TEXT,
    captcha_threshold NUMERIC(3,2) DEFAULT 0.5,
    enable_rate_limiting BOOLEAN NOT NULL DEFAULT true,
    rate_limit_requests_per_minute INTEGER NOT NULL DEFAULT 60,
    rate_limit_burst_size INTEGER DEFAULT 100,
    ip_whitelist INET[],
    ip_blacklist INET[],
    enable_ip_geolocation BOOLEAN NOT NULL DEFAULT false,
    blocked_countries TEXT[],
    allowed_countries TEXT[],
    file_storage_provider storage_provider_type NOT NULL DEFAULT 'local',
    file_storage_path TEXT DEFAULT '/app/storage',
    max_file_size_bytes BIGINT NOT NULL DEFAULT 10485760,
    max_total_storage_bytes BIGINT,
    allowed_mime_types TEXT[] DEFAULT ARRAY['image/jpeg','image/png','image/gif','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/zip'],
    blocked_mime_types TEXT[] DEFAULT ARRAY['application/x-executable','application/x-msdos-program'],
    enable_virus_scanning BOOLEAN NOT NULL DEFAULT false,
    virus_scan_provider TEXT,
    aws_s3_bucket TEXT,
    aws_s3_region TEXT,
    aws_s3_access_key_encrypted TEXT,
    aws_s3_secret_key_encrypted TEXT,
    aws_s3_public_url TEXT,
    cdn_enabled BOOLEAN NOT NULL DEFAULT false,
    cdn_url TEXT,
    api_enabled BOOLEAN NOT NULL DEFAULT true,
    api_rate_limit_enabled BOOLEAN NOT NULL DEFAULT true,
    api_rate_limit_requests_per_minute INTEGER DEFAULT 100,
    api_timeout_seconds INTEGER NOT NULL DEFAULT 30,
    api_max_payload_size_bytes INTEGER DEFAULT 1048576,
    enable_api_documentation BOOLEAN NOT NULL DEFAULT true,
    api_documentation_url TEXT,
    enable_cors BOOLEAN NOT NULL DEFAULT true,
    cors_allowed_origins TEXT[],
    cors_allowed_methods TEXT[] DEFAULT ARRAY['GET','POST','PUT','DELETE','PATCH'],
    cors_allowed_headers TEXT[] DEFAULT ARRAY['Content-Type','Authorization'],
    cors_max_age_seconds INTEGER DEFAULT 86400,
    log_level log_level_type NOT NULL DEFAULT 'info',
    enable_audit_logging BOOLEAN NOT NULL DEFAULT true,
    log_retention_days INTEGER NOT NULL DEFAULT 90,
    log_sensitive_data BOOLEAN NOT NULL DEFAULT false,
    enable_error_tracking BOOLEAN NOT NULL DEFAULT false,
    sentry_dsn_encrypted TEXT,
    sentry_environment TEXT,
    sentry_sample_rate NUMERIC(3,2) DEFAULT 1.0,
    enable_performance_monitoring BOOLEAN NOT NULL DEFAULT false,
    performance_sample_rate NUMERIC(3,2) DEFAULT 0.1,
    enable_auto_backup BOOLEAN NOT NULL DEFAULT true,
    backup_schedule TEXT DEFAULT '0 2 * * *',
    backup_retention_days INTEGER NOT NULL DEFAULT 30,
    backup_storage_provider storage_provider_type DEFAULT 'local',
    backup_storage_path TEXT DEFAULT '/app/backups',
    backup_encryption_enabled BOOLEAN NOT NULL DEFAULT true,
    backup_compression_enabled BOOLEAN NOT NULL DEFAULT true,
    maintenance_mode BOOLEAN NOT NULL DEFAULT false,
    maintenance_message TEXT,
    maintenance_allowed_ips INET[],
    maintenance_start_time TIMESTAMPTZ,
    maintenance_end_time TIMESTAMPTZ,
    default_language TEXT NOT NULL DEFAULT 'en',
    available_languages TEXT[] DEFAULT ARRAY['en'],
    default_timezone TEXT NOT NULL DEFAULT 'UTC',
    default_currency_code TEXT DEFAULT 'USD',
    default_date_format TEXT DEFAULT 'YYYY-MM-DD',
    default_time_format TEXT DEFAULT 'HH:mm:ss',
    enable_registration BOOLEAN NOT NULL DEFAULT true,
    registration_requires_approval BOOLEAN NOT NULL DEFAULT false,
    registration_auto_verify_email BOOLEAN NOT NULL DEFAULT false,
    default_user_role TEXT,
    enable_invitations BOOLEAN NOT NULL DEFAULT true,
    invitation_expiry_hours INTEGER DEFAULT 72,
    terms_version TEXT,
    terms_last_updated TIMESTAMPTZ,
    privacy_version TEXT,
    privacy_last_updated TIMESTAMPTZ,
    cookie_consent_enabled BOOLEAN NOT NULL DEFAULT true,
    gdpr_compliant BOOLEAN NOT NULL DEFAULT true,
    data_retention_days INTEGER,
    enable_data_export BOOLEAN NOT NULL DEFAULT true,
    enable_account_deletion BOOLEAN NOT NULL DEFAULT true,
    system_version TEXT,
    deployment_environment TEXT DEFAULT 'production',
    feature_flags JSONB NOT NULL DEFAULT '{}'::jsonb,
    custom_settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.users(id),
    updated_by UUID REFERENCES public.users(id),
    CONSTRAINT password_length_valid CHECK (password_min_length >= 6 AND password_min_length <= password_max_length),
    CONSTRAINT session_timeout_valid CHECK (session_timeout_minutes > 0 AND session_timeout_minutes <= 1440),
    CONSTRAINT smtp_port_valid CHECK (smtp_port > 0 AND smtp_port <= 65535),
    CONSTRAINT rate_limit_valid CHECK (rate_limit_requests_per_minute > 0),
    CONSTRAINT max_file_size_valid CHECK (max_file_size_bytes > 0),
    CONSTRAINT api_timeout_valid CHECK (api_timeout_seconds > 0 AND api_timeout_seconds <= 300),
    CONSTRAINT backup_retention_valid CHECK (backup_retention_days >= 1),
    CONSTRAINT log_retention_valid CHECK (log_retention_days >= 1),
    CONSTRAINT sample_rate_valid CHECK (sentry_sample_rate >= 0 AND sentry_sample_rate <= 1 AND performance_sample_rate >= 0 AND performance_sample_rate <= 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_settings_singleton ON public.system_settings((1));

INSERT INTO public.system_settings (
    system_name, 
    system_tagline, 
    system_description,
    logo_light_url,
    logo_dark_url
) VALUES (
    'BuildFlow ERP',
    'Complete Business Management Solution',
    'A comprehensive ERP system for managing your business operations',
    '/images/landing/light.svg',
    '/images/landing/logo.svg'
) ON CONFLICT DO NOTHING;

DROP TRIGGER IF EXISTS update_system_settings_updated_at ON public.system_settings;
CREATE TRIGGER update_system_settings_updated_at
    BEFORE UPDATE ON public.system_settings
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();
