export const selectRecords = async <T = any>(...args: any[]): Promise<any> => ({ data: [], error: null, success: true });
export const selectOne = async <T = any>(...args: any[]): Promise<any> => ({ data: null, error: null, success: true });
export const insertRecord = async <T = any>(...args: any[]): Promise<any> => ({ data: null, error: null, success: true });
export const updateRecord = async <T = any>(...args: any[]): Promise<any> => ({ data: null, error: null, success: true });
export const deleteRecord = async <T = any>(...args: any[]): Promise<any> => ({ data: null, error: null, success: true });
export const executeTransaction = async <T = any>(...args: any[]): Promise<any> => ({ data: null, error: null, success: true });
export const rawQuery = async <T = any>(...args: any[]): Promise<any> => ({ data: [], error: null, success: true });
export const rawQueryOne = async <T = any>(...args: any[]): Promise<any> => ({ data: null, error: null, success: true });
export const countRecords = async <T = any>(...args: any[]): Promise<any> => ({ data: 0, error: null, success: true });
