/**
 * Icon name string to Lucide component map.
 * Used by sidebar nav and header (breadcrumbs, command palette).
 */

import type React from 'react';
import {
  Building,
  Users,
  Calculator,
  DollarSign,
  User,
  FileText,
  Calendar,
  Settings,
  BarChart3,
  ClipboardList,
  Clock,
  UserCheck,
  CreditCard,
  Receipt,
  BookOpen,
  Building2,
  ChartLine,
  Briefcase,
  Users2,
  FileCheck,
  Monitor,
  FolderKanban,
  CalendarDays,
  UserCog,
  Settings2,
  UserPlus,
  TrendingUp,
  Bell,
  Package,
  ShoppingCart,
  Mail,
  Warehouse,
  ArrowRightLeft,
  Edit,
  Hash,
  PackageCheck,
  FileSearch,
  FolderTree,
  MapPin,
  Wrench,
  TrendingDown,
  Trash2,
  GitBranch,
  CheckCircle2,
  Zap,
  Plug,
  Download,
  Activity,
  Layers,
  ShoppingBag,
  FileBarChart,
  Boxes,
  Truck,
  Handshake,
  Target,
  Workflow,
  Network,
  Database,
  Server,
  Shield,
  Cog,
  Eye,
  Home,
  Search,
  LogOut,
  HelpCircle,
  Wifi,
  WifiOff,
  Moon,
  Sun,
} from 'lucide-react';

export type IconComponent = React.ComponentType<{ className?: string }>;

export const iconMap: Record<string, IconComponent> = {
  Monitor,
  BarChart3,
  Users,
  Users2,
  User,
  Building,
  Building2,
  Calculator,
  DollarSign,
  Calendar,
  Clock,
  TrendingUp,
  AlertCircle: Clock,
  CalendarDays,
  Shield,
  ChevronRight: Clock,
  Bell,
  Briefcase,
  FileText,
  Settings,
  BookOpen,
  ChartLine,
  CreditCard,
  Receipt,
  ClipboardList,
  FolderKanban,
  UserCog,
  Settings2,
  UserPlus,
  FileCheck,
  Package,
  ShoppingCart,
  Mail,
  Warehouse,
  ArrowRightLeft,
  Edit,
  Hash,
  PackageCheck,
  FileSearch,
  FolderTree,
  MapPin,
  Wrench,
  TrendingDown,
  Trash2,
  GitBranch,
  CheckCircle2,
  Zap,
  Plug,
  Download,
  Activity,
  Layers,
  ShoppingBag,
  FileBarChart,
  Boxes,
  Truck,
  Handshake,
  Target,
  Workflow,
  Network,
  Database,
  Server,
  Cog,
  Eye,
  Home,
  Search,
  LogOut,
  HelpCircle,
  Wifi,
  WifiOff,
  Moon,
  Sun,
};

export function getIcon(name: string): IconComponent {
  return iconMap[name] ?? User;
}

/** Route path to icon name for header current-page icon */
const routeToIconName: Record<string, string> = {
  '/dashboard': 'Home',
  '/employees': 'Users',
  '/projects': 'Briefcase',
  '/attendance': 'Calendar',
  '/payroll': 'DollarSign',
  '/clients': 'Users',
  '/crm': 'Briefcase',
  '/financial-management': 'DollarSign',
  '/reports': 'FileText',
  '/analytics': 'BarChart3',
  '/settings': 'Settings',
  '/my-profile': 'User',
  '/system-dashboard': 'Shield',
};

export function getPageIcon(path: string): IconComponent {
  return getIcon(routeToIconName[path] ?? 'FileText');
}
